#!/usr/bin/env python3
import subprocess, os, requests, time, base64
ROOT = os.path.dirname(os.path.abspath(__file__))
API_KEY = "sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL = "https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status(); return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1: time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=[
 "Ancient Chinese mountain temple in mist, a Buddhist monk in meditation on Lushan mountain, peaceful and wise, traditional Chinese ink wash painting, Song dynasty aesthetic, jade green and gold tones, spiritual atmosphere",
 "Ancient Chinese debate scene, a Buddhist monk calmly facing a powerful official in court, intellectual confrontation, traditional Chinese ink wash painting, warm amber and gold tones, dramatic and philosophical atmosphere",
 "Ancient Chinese imperial court, officials arguing with a Buddhist monk about whether monks should bow to the emperor, traditional Chinese ink wash painting, dark red and gold tones, tense intellectual atmosphere",
 "Symbolic scene: a Buddhist monk standing tall while emperors and officials bow before him, representing the independence of the spirit from political power, traditional Chinese ink wash painting, spiritual and majestic, gold tones"]
FILES=["hy-cover","hy-card-1","hy-card-2","hy-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#22C55E" letter-spacing="6" {STROKE}>东晋佛教·思想自由</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>慧远</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#22C55E" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="38" font-weight="800" fill="#22C55E" letter-spacing="4" {STROKE}>沙门不敬王者</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>庐山三十年·僧人不必跪拜皇帝</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#慧远 #沙门不敬王者 #东晋 #佛教 #庐山</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>庐山大德</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>儒入佛</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>精通六经的儒家学者，后皈依佛门</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>三十年不下山</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>庐山隐居三十多年，潜心译经修行</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>影响力</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>东晋政界学界都来向他请教</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>不出山而影响天下</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#慧远 #庐山 #佛教 #东晋</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>沙门不敬王者论</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>桓玄发难</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>权臣要求僧人必须向皇帝行跪拜礼</text></g><g transform="translate(40,300)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>慧远反击</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>写《沙门不敬王者论》正面硬刚</text></g><g transform="translate(40,445)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>核心论点</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>沙门已脱离世俗，不是臣民，是求道者</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>僧人不必跪拜皇帝——桓玄最终妥协</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#沙门不敬王者 #桓玄 #慧远 #佛教</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>千年影响</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="120" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="120" rx="3" fill="#22C55E"/><text x="30" y="42" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>佛教不跪皇帝</text><text x="30" y="82" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>慧远确立的原则影响中国佛教</text><text x="30" y="110" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>一千多年至今</text></g><g transform="translate(40,340)"><rect x="0" y="0" width="944" height="120" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="120" rx="3" fill="#22C55E"/><text x="30" y="42" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>思维的边界</text><text x="30" y="82" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>在皇权至上的时代划出界限——</text><text x="30" y="110" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>有些事不归皇帝管</text></g><text x="512" y="600" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>魏晋南北朝思想自由的高光时刻</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#慧远 #思想自由 #东晋 #魏晋风度</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w",encoding="utf-8") as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024} KB)")
 print("Done!")
