#!/usr/bin/env python3
import subprocess, os, requests, time, base64
ROOT = os.path.dirname(os.path.abspath(__file__))
API_KEY = "sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL = "https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status(); return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1: time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=[
 "Ancient Chinese palace interior, a young emperor playing as a market vendor in golden robes inside his own palace, bizarre and decadent scene, traditional Chinese ink wash painting, Song dynasty aesthetic, gold and dark red tones, satirical atmosphere",
 "Ancient Chinese palace scene, golden lotus flowers embedded in the floor, a beautiful woman walking on them, luxurious and decadent, traditional Chinese ink wash painting, gold and pink tones, surreal atmosphere",
 "Ancient Chinese scene of a young emperor building extravagant structures at night, obsessed with construction projects, traditional Chinese ink wash painting, dark amber and gray tones, obsessive atmosphere",
 "Ancient Chinese palace, rebels storming the gates while the emperor plays unconcerned, dramatic irony, traditional Chinese ink wash painting, dark red and black tones, tragicomic atmosphere"]
FILES=["xbj-cover","xbj-card-1","xbj-card-2","xbj-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#E11D48" letter-spacing="6" {STROKE}>南齐·荒唐皇帝</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>萧宝卷</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#E11D48" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="34" font-weight="800" fill="#E11D48" letter-spacing="4" {STROKE}>手工耿·步步生莲</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>皇宫里摆摊卖菜的金莲皇帝</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#萧宝卷 #步步生莲 #南齐 #荒唐皇帝</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#E11D48" letter-spacing="3" {STROKE}>天生的废物</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#E11D48"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>爹的遗言</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>"做皇帝先杀人，杀到没人敢反抗为止"</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#E11D48"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>杀光重臣</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>六位辅政大臣全杀，然后开始专职玩</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#E11D48"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>不务正业</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>不上朝不理政，天天搞工程</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>他爹萧鸾要是还在，估计能气活</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#萧宝卷 #南齐 #萧鸾 #荒唐皇帝</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>步步生莲</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>皇宫里的市场</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>建大市场扮摊贩，宫女扮顾客</text></g><g transform="translate(40,275)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>仙华殿</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>黄金白玉铺地，极尽奢华</text></g><g transform="translate(40,395)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>金莲步</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>黄金雕莲花嵌在地板，让潘玉儿走</text></g><g transform="translate(40,515)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>半夜劫富</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>带人出去抢老百姓财物</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>手工耿看了都要说一句"还得是你"</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#步步生莲 #萧宝卷 #潘玉儿 #手工耿</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#EF4444" letter-spacing="3" {STROKE}>终结</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#EF4444"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>萧衍起兵</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>501年，萧衍（后来的梁武帝）起兵讨伐</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#EF4444"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>还在卖菜</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>听说叛军来了，以为对方要抢他生意</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#EF4444"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>被手下杀死</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>19岁，南齐灭亡。遗言："我还没玩够"</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>中国历史上最不正经的皇帝之一</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#萧衍 #南齐灭亡 #萧宝卷 #荒唐皇帝</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w",encoding="utf-8") as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024} KB)")
 print("Done!")
