#!/usr/bin/env python3
import subprocess, os, requests, time, base64
ROOT = os.path.dirname(os.path.abspath(__file__))
API_KEY = "sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL = "https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status(); return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1: time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=[
 "Ancient Chinese palace scene, a powerful empress dowager in regal purple robes ordering the poisoning of her own son, dark and tragic atmosphere, traditional Chinese ink wash painting, Song dynasty aesthetic, deep purple and crimson tones, dramatic lighting",
 "Ancient Chinese palace scene, a young girl in imperial robes being placed on a throne, confused and frightened, surrounded by court officials, traditional Chinese ink wash painting, dim candlelight, dark gold and gray tones, tragic atmosphere",
 "Ancient Chinese battle scene, a general on horseback leading troops into a capital city, chaos and destruction, traditional Chinese ink wash painting, dark red and black tones, epic war atmosphere, Song dynasty aesthetic",
 "Symbolic scene: a powerful woman being thrown into the Yellow River, tragic end of a dynasty, traditional Chinese ink wash painting, dark blue and gray tones, somber and dramatic, Song dynasty aesthetic"]
FILES=["ht-cover","ht-card-1","ht-card-2","ht-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#A855F7" letter-spacing="6" {STROKE}>北魏权力女性</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>胡太后</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#A855F7" opacity="0.6"/><text x="512" y="480" text-anchor="middle" font-family="{FONT}" font-size="34" font-weight="800" fill="#A855F7" letter-spacing="4" {STROKE}>杀子·立女帝·第一女皇</text><text x="512" y="600" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>她立了一个女皇帝·比武则天早150年</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#胡太后 #北魏 #第一个女皇帝 #尔朱荣</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#A855F7" letter-spacing="3" {STROKE}>子贵母死·她活下来了</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#A855F7"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#A855F7" {STROKE}>生子元诩</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>按规矩该处死，但因帝幼母存，破例</text></g><g transform="translate(40,300)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#A855F7"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#A855F7" {STROKE}>临朝称制</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>精明强干，有政治手腕，但贪婪狠辣</text></g><g transform="translate(40,445)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#A855F7"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#A855F7" {STROKE}>母子反目</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>孝明帝长大夺权，她先下手为强</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#A855F7" {STROKE}>她亲手毒死了自己19岁的亲生儿子</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#子贵母死 #北魏 #胡太后 #孝明帝</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>中国第一个女皇帝</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>孝明帝无子</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>只有两个女儿，没有儿子继位</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>伪装的皇子</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>把孝明帝女儿伪装成男孩立为皇帝</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>仅几天就被废</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>史料含糊，但这个无名女孩才是第一女皇</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>比武则天称帝早了150多年</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#第一个女皇帝 #武则天 #胡太后 #北魏</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#EF4444" letter-spacing="3" {STROKE}>黄河收场</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#EF4444"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>尔朱荣清君侧</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>以杀太后为名起兵攻入洛阳</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#EF4444"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>黄河沉尸</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>胡太后和幼帝被扔进黄河淹死</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#EF4444"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>河阴之变</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>两千朝臣被杀，北魏从此名存实亡</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#EF4444" {STROKE}>权力游戏里没有赢家</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#尔朱荣 #河阴之变 #胡太后 #北魏</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w",encoding="utf-8") as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024} KB)")
 print("Done!")
