#!/usr/bin/env python3
import subprocess,os,requests,time,base64
ROOT=os.path.dirname(os.path.abspath(__file__))
API_KEY="sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL="https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status();return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1:time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=["Ancient Chinese bamboo grove, seven scholars drinking and discussing philosophy, traditional Chinese ink wash painting, Song dynasty aesthetic, jade green and gold tones, elegant and free-spirited atmosphere","Ancient Chinese scene of a wise scholar serving as a government minister, reviewing documents and selecting talented officials, traditional Chinese ink wash painting, warm amber tones, dignified atmosphere","Ancient Chinese scene of emotional farewell: a dying scholar entrusting his son to another, trust and brotherhood, traditional Chinese ink wash painting, warm golden tones, touching atmosphere","Symbolic scene: a bridge connecting the reclusive life of the bamboo grove with the responsibilities of government service, integrity in both worlds, traditional Chinese ink wash painting, philosophical atmosphere, blue and green tones"]
FILES=["st-cover","st-card-1","st-card-2","st-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#22C55E" letter-spacing="6" {STROKE}>竹林七贤</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>山涛</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#22C55E" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="34" font-weight="800" fill="#22C55E" letter-spacing="4" {STROKE}>山公尚在·汝不孤矣</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>嵇康绝交后托孤·竹林中最靠谱的人</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#山涛 #竹林七贤 #山公尚在 #嵇康 #魏晋风度</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>竹林七贤之长</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>最年长的隐士</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>竹林中最年长，清醒通透</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>隐逸只是暂时的</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>他知道天下终究需要有人做事</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>与嵇康绝交</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>嵇康写《与山巨源绝交书》后仍托孤</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>包容了绝交，却依然照顾家人</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#山涛 #竹林七贤 #嵇康 #绝交书</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>吏部尚书三十年</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>出山当官</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>西晋吏部尚书，只看才能不管出身</text></g><g transform="translate(40,275)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>选拔大量人才</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>为西晋选出了真正能干的大臣</text></g><g transform="translate(40,395)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>清正廉洁</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>做了三十年，从无徇私</text></g><g transform="translate(40,515)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#F59E0B"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>后世典范</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>后代把他当作"清官"的标杆</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="24" font-weight="700" fill="#F59E0B" {STROKE}>隐能入竹林，仕能清天下</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#山涛 #西晋 #吏部 #清官</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#38BDF8" letter-spacing="3" {STROKE}>山公尚在·汝不孤矣</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>嵇康临终托孤</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>"山公尚在，汝不孤矣"</text></g><g transform="translate(40,275)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>为什么信他</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>嵇康和山涛绝交却仍托付儿子</text></g><g transform="translate(40,395)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>最可靠的人</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>竹林七贤中，山涛是最让人安心的</text></g><g transform="translate(40,515)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>一生的写照</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>让所有人都不孤独的人</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>竹林七贤中有人烈有人狂，但山涛让人安心</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#山公尚在 #嵇康 #托孤 #竹林七贤 #魏晋</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w")as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024}KB)")
 print("Done!")
