#!/usr/bin/env python3
import subprocess,os,requests,time,base64
ROOT=os.path.dirname(os.path.abspath(__file__))
API_KEY="sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL="https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status();return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1:time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=["Ancient Chinese military camp, a rebel general praying to Buddha statues instead of preparing for battle, absurd scene, traditional Chinese ink wash painting, Song dynasty aesthetic, dark red and gold tones, ironic atmosphere","Ancient Chinese battle scene, rebels marching toward the capital city, burning palaces, traditional Chinese ink wash painting, dark red and gray tones, chaotic atmosphere","Ancient Chinese scene: a general kneeling before Buddha statues while enemy troops approach, praying for a miracle instead of fighting, traditional Chinese ink wash painting, dark amber tones, tragicomic atmosphere","Symbolic scene: a fallen general on the battlefield, Buddha statues looking on impassively, lesson that gods dont save those who dont help themselves, traditional Chinese ink wash painting, dark and philosophical tones"]
FILES=["sjzl-cover","sjzl-card-1","sjzl-card-2","sjzl-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#F59E0B" letter-spacing="6" {STROKE}>东晋·奇葩战史</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>苏峻之乱</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#F59E0B" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="34" font-weight="800" fill="#F59E0B" letter-spacing="4" {STROKE}>指望佛祖显灵</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>打不过就拜佛——佛祖没有显灵</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#苏峻之乱 #东晋 #佛教 #佛祖显灵 #奇葩</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>谁是苏峻</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>东晋将领</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>平定王敦之乱立了大功</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>起兵造反</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>觉得功劳大赏赐少，起兵攻入建康</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>烧皇宫扣皇帝</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>抓朝廷官员，小皇帝当人质</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>造反水平很高，但后面走偏了</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#苏峻 #东晋 #王敦 #建康</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#EF4444" letter-spacing="3" {STROKE}>最离谱的操作</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#EF4444"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#EF4444" {STROKE}>不派兵防守</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>朝廷军队打回来，他毫无军事部署</text></g><g transform="translate(40,275)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#EF4444"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#EF4444" {STROKE}>摆佛像拜佛</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>在军营中摆上佛像，全军跪拜祈祷</text></g><g transform="translate(40,395)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#EF4444"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#EF4444" {STROKE}>相信佛祖显灵</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>认为敌人会"放下屠刀"</text></g><g transform="translate(40,515)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#EF4444"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#EF4444" {STROKE}>逃亡被射死</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>佛祖没显灵，逃跑时被射杀</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="24" font-weight="700" fill="#EF4444" {STROKE}>佛祖保佑不了胡搞的人</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#苏峻之乱 #佛祖显灵 #东晋 #佛教</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>时代背景</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>佛教快速普及</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>上至皇帝下至百姓，全民信佛</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>苏峻的荒谬不稀奇</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>在那个时代，拜佛求胜利是常规操作</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>侧面印证信仰力量</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>佛教在东晋社会各阶层的影响力之深</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>一个将军在战场上拜佛等赢</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#苏峻之乱 #佛教 #东晋 #奇葩历史</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w")as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024}KB)")
 print("Done!")
