#!/usr/bin/env python3
import subprocess,os,requests,time,base64
ROOT=os.path.dirname(os.path.abspath(__file__))
API_KEY="sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL="https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status();return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1:time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=["Ancient Chinese temple wall, a master painter putting finishing touches on a dragon painting, dramatic moment of creation, traditional Chinese ink wash painting, Song dynasty aesthetic, ink and gold tones, epic atmosphere","Ancient Chinese myth scene: painted dragons on a wall suddenly coming to life, breaking through the wall and flying into stormy sky, traditional Chinese ink wash painting, dark and dramatic, blue-gray storm tones","Ancient Chinese painter's studio, a master artist using bold brush techniques creating Buddhist frescoes, traditional Chinese ink wash painting, warm amber and gold tones, artistic atmosphere","Symbolic scene: three great masters of Chinese painting - Gu Kaizhi, Lu Tanwei, Zhang Sengyou - comparing their art, traditional Chinese ink wash painting, philosophical atmosphere, ink wash tones"]
FILES=["zsy-cover","zsy-card-1","zsy-card-2","zsy-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#F59E0B" letter-spacing="6" {STROKE}>南朝梁·成语故事</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>张僧繇</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#F59E0B" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="38" font-weight="800" fill="#F59E0B" letter-spacing="4" {STROKE}>画龙点睛</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>点睛即飞去·六朝三大家</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#张僧繇 #画龙点睛 #南朝 #六朝 #中国画</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>梁朝第一画师</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>梁武帝御用画师</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>所有寺庙壁画几乎都交给他</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>凹凸花</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>吸收印度晕染法，画法前所未有大膽</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>六朝三大家</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>与顾恺之、陆探微齐名</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>张得其肉·陆得其骨·顾得其神</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#张僧繇 #顾恺之 #绘画 #六朝</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#38BDF8" letter-spacing="3" {STROKE}>画龙点睛</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>安乐寺画龙</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>金陵安乐寺墙上画了四条龙</text></g><g transform="translate(40,275)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>不点眼睛</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>"点睛即飞去"——大家都笑他吹牛</text></g><g transform="translate(40,395)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>破壁飞去</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>刚点完眼睛，电闪雷鸣，龙破壁飞去</text></g><g transform="translate(40,515)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>没点睛的两条</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>至今还在墙上</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>最后一笔让作品活起来</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#画龙点睛 #成语 #张僧繇 #安乐寺</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>千年影响</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>画作大多失传</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>但艺术理念影响了中国绘画千年</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>成语传承</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>"画龙点睛"——点到关键处的极致</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#22C55E"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>文人画的源头</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>张僧繇的画法影响了唐以后文人画</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>不画眼睛不是不会画，是怕画了会飞</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#张僧繇 #文人画 #中国艺术 #成语</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w")as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024}KB)")
 print("Done!")
