#!/usr/bin/env python3
import subprocess, os, requests, time, base64
ROOT = os.path.dirname(os.path.abspath(__file__))
API_KEY = "sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL = "https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status(); return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1: time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=[
 "Ancient Chinese palace scene, a beautiful imperial consort applying makeup to only half her face, mirror reflection, dramatic and rebellious atmosphere, traditional Chinese ink wash painting, Song dynasty aesthetic, rose and gold tones, poetic tension",
 "Ancient Chinese scene of an emperor with one eye visiting his consort, she only applies makeup to half her face, tense palace drama, traditional Chinese ink wash painting, dark vermilion and gray tones, uncomfortable atmosphere",
 "Ancient Chinese palace garden scene, a rebellious consort drinking wine and behaving scandalously, traditional Chinese ink wash painting, warm amber and rose tones, decadent atmosphere",
 "Symbolic scene: a woman falling into a well, surrounded by palace walls, tragic end of a defiant life, traditional Chinese ink wash painting, dark blue and gray tones, melancholic atmosphere"]
FILES=["xzp-cover","xzp-card-1","xzp-card-2","xzp-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#E11D48" letter-spacing="6" {STROKE}>南朝·成语故事</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="80" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>徐昭佩</text><rect x="312" y="370" width="400" height="3" rx="1.5" fill="#E11D48" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="38" font-weight="800" fill="#E11D48" letter-spacing="4" {STROKE}>徐娘半老·半面妆</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>你只有一只眼睛，看半面就够了</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#徐昭佩 #徐娘半老 #半面妆 #梁元帝 #萧绎</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#E11D48" letter-spacing="3" {STROKE}>半面妆的挑衅</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="130" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="130" rx="3" fill="#E11D48"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>梁元帝萧绎</text><text x="30" y="84" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>才子皇帝，诗词书画三绝</text><text x="30" y="112" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>但一只眼睛失明</text></g><g transform="translate(40,345)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#E11D48"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>半面妆</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>她只化半张脸的妆——左脸精致右脸素颜</text></g><g transform="translate(40,490)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#E11D48"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>羞辱</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>"你只有一只眼，看半面就够了"</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#E11D48" {STROKE}>不是情趣，是赤裸裸的羞辱</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#半面妆 #徐昭佩 #梁元帝 #萧绎</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>摆烂的人生</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>酗酒</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>每次萧绎来就喝得大醉，吐在龙袍上</text></g><g transform="translate(40,300)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>绿帽子</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>与僧人私通，与萧绎部下私通</text></g><g transform="translate(40,445)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>忍无可忍</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>萧绎忍了十几年，最后逼令自杀</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>投井而亡，尸体被送还徐家——出妻</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#徐昭佩 #古代女性 #南朝 #摆烂</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>成语的诞生</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="120" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="120" rx="3" fill="#22C55E"/><text x="30" y="42" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>李商隐的诗</text><text x="30" y="82" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>"休夸此地分天下，只得徐妃半面妆"</text><text x="30" y="110" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>——《南朝》</text></g><g transform="translate(40,340)"><rect x="0" y="0" width="944" height="120" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="120" rx="3" fill="#22C55E"/><text x="30" y="42" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>徐娘半老·风韵犹存</text><text x="30" y="82" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>一个被黑了一千多年的女人</text><text x="30" y="110" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>最后活成了两个成语</text></g><text x="512" y="600" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>半面妆和徐娘半老——讽刺的成名方式</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#徐娘半老 #半面妆 #成语 #李商隐 #徐昭佩</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w",encoding="utf-8") as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024} KB)")
 print("Done!")
