#!/usr/bin/env python3
import subprocess, os, requests, time, base64
ROOT = os.path.dirname(os.path.abspath(__file__))
API_KEY = "sk-YjJnlziWMJgYHmiJiX8peB5PtNx1hInu7SQnivjeavaN4Ect"
API_URL = "https://apihub.agnes-ai.com/v1/images/generations"
STROKE='paint-order="stroke fill" stroke="#000" stroke-width="5" stroke-linejoin="round"'
STROKE_S='paint-order="stroke fill" stroke="#000" stroke-width="3" stroke-linejoin="round"'
FONT='Noto Sans SC,PingFang SC,Microsoft YaHei,sans-serif'
def agnes(prompt,size="1024x1024",retries=3):
 for a in range(retries):
  try:
   r=requests.post(API_URL,headers={"Authorization":f"Bearer {API_KEY}","Content-Type":"application/json"},json={"model":"agnes-image-2.1-flash","prompt":prompt,"size":size,"n":1},timeout=120)
   r.raise_for_status(); return requests.get(r.json()["data"][0]["url"],timeout=60).content
  except Exception as e:
   print(f"  attempt {a+1} failed: {e}")
   if a<retries-1: time.sleep(5)
 raise RuntimeError("Failed")
PROMPTS=[
 "Ancient Chinese royal court scene, a ruler changing names on a registry, officials receiving new Xianbei-style names, ceremonial atmosphere, traditional Chinese ink wash painting, Song dynasty aesthetic, gold and blue tones, political drama",
 "Ancient Chinese military camp, Xianbei and Han generals together, a political alliance being forged through name changes and marriage ties, traditional Chinese ink wash painting, warm amber tones, strategic atmosphere",
 "Ancient Chinese scene showing the contrast between a Han official's old and new name carved on two seals, traditional Chinese ink wash painting, Song dynasty aesthetic, muted gold and gray tones",
 "Symbolic scene of names floating between Han Chinese and Xianbei identity, a bridge between two cultures, traditional Chinese ink wash painting, philosophical atmosphere, blue and gold tones"]
FILES=["gfx-cover","gfx-card-1","gfx-card-2","gfx-card-3"]
def svg(bg,text):
 return f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="ovG" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="30%" stop-color="#000" stop-opacity="0.15"/><stop offset="100%" stop-color="#000" stop-opacity="0.65"/></linearGradient></defs><image href="data:image/png;base64,{bg}" x="0" y="0" width="1024" height="1024" preserveAspectRatio="xMidYMid slice"/><rect x="0" y="0" width="1024" height="1024" fill="url(#ovG)"/>{text}</svg>'
def c0(bg):
 return svg(bg,f'<text x="512" y="160" text-anchor="middle" font-family="{FONT}" font-size="28" font-weight="700" fill="#F59E0B" letter-spacing="6" {STROKE}>西魏·政治改名</text><text x="512" y="330" text-anchor="middle" font-family="{FONT}" font-size="72" font-weight="900" fill="#FFFFFF" letter-spacing="8" {STROKE}>复古改姓运动</text><rect x="212" y="370" width="600" height="3" rx="1.5" fill="#F59E0B" opacity="0.6"/><text x="512" y="500" text-anchor="middle" font-family="{FONT}" font-size="38" font-weight="800" fill="#F59E0B" letter-spacing="4" {STROKE}>汉人改鲜卑姓</text><text x="512" y="620" text-anchor="middle" font-family="{FONT}" font-size="24" fill="#E2E8F0" {STROKE_S}>李虎→大野虎·杨坚→普六茹坚·关陇集团的起点</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#西魏 #宇文泰 #关陇集团 #改姓 #大野 #普六茹</text>')
def c1(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#F59E0B" letter-spacing="3" {STROKE}>为什么"复古改姓"</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>元宏汉化→宇文泰鲜卑化</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>孝文帝让鲜卑改汉姓，宇文泰反着来</text></g><g transform="translate(40,330)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>打造鲜卑联盟</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>团结六镇军人和关陇集团对抗东魏</text></g><g transform="translate(40,480)"><rect x="0" y="0" width="944" height="110" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="110" rx="3" fill="#F59E0B"/><text x="30" y="44" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>政治认同</text><text x="30" y="80" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>用新姓氏创造新的政治身份</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#F59E0B" {STROKE}>宇文泰不是复古，是在造人</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#宇文泰 #关陇集团 #西魏 #北魏</text>')
def c2(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#38BDF8" letter-spacing="3" {STROKE}>改姓名单</text><g transform="translate(40,155)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>李虎→大野氏</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>李渊的祖父→"大野虎"</text></g><g transform="translate(40,275)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>杨坚→普六茹氏</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>隋文帝→"普六茹坚"</text></g><g transform="translate(40,395)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>赵贵、李弼、于谨、独孤信</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>关陇集团核心全部赐姓</text></g><g transform="translate(40,515)"><rect x="0" y="0" width="944" height="95" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="95" rx="3" fill="#38BDF8"/><text x="30" y="38" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>隋朝后全部改回</text><text x="30" y="70" font-family="{FONT}" font-size="20" fill="#E2E8F0" {STROKE_S}>但"宇文"这个名字留到了唐朝</text></g><text x="512" y="720" text-anchor="middle" font-family="{FONT}" font-size="24" font-weight="700" fill="#38BDF8" {STROKE}>名字变了，人没变——权力才是真正的姓</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#独孤信 #杨坚 #李虎 #关陇集团 #鲜卑</text>')
def c3(bg):
 return svg(bg,f'<rect x="0" y="0" width="1024" height="110" fill="#0F172A" opacity="0.88"/><text x="512" y="72" text-anchor="middle" font-family="{FONT}" font-size="36" font-weight="800" fill="#22C55E" letter-spacing="3" {STROKE}>历史影响</text><g transform="translate(40,180)"><rect x="0" y="0" width="944" height="120" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="120" rx="3" fill="#22C55E"/><text x="30" y="42" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>关陇集团诞生</text><text x="30" y="82" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>改姓运动把胡汉精英凝聚成</text><text x="30" y="110" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>新的利益共同体</text></g><g transform="translate(40,340)"><rect x="0" y="0" width="944" height="120" rx="14" fill="#0F172A" opacity="0.82"/><rect x="0" y="0" width="6" height="120" rx="3" fill="#22C55E"/><text x="30" y="42" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>孕育隋唐</text><text x="30" y="82" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>北周→隋→唐的统治阶层</text><text x="30" y="110" font-family="{FONT}" font-size="22" fill="#E2E8F0" {STROKE_S}>全是从这个集团里走出来的</text></g><text x="512" y="600" text-anchor="middle" font-family="{FONT}" font-size="26" font-weight="700" fill="#22C55E" {STROKE}>名字是政治工具——宇文泰深谙此道</text><text x="512" y="960" text-anchor="middle" font-family="{FONT}" font-size="18" fill="#94A3B8" {STROKE_S}>#关陇集团 #隋 #唐 #西魏 #宇文泰</text>')
if __name__=="__main__":
 os.makedirs(ROOT,exist_ok=True)
 makers=[c0,c1,c2,c3]
 for i,p in enumerate(PROMPTS):
  n=FILES[i];print(f"  Agnes {n}...")
  d=agnes(p);b=base64.b64encode(d).decode();s=makers[i](b)
  with open(os.path.join(ROOT,f"{n}.svg"),"w",encoding="utf-8") as f:f.write(s)
  subprocess.run(["inkscape",os.path.join(ROOT,f"{n}.svg"),"-o",os.path.join(ROOT,f"{n}.png"),"-w","1024","-h","1024"],check=True,capture_output=True)
  print(f"  {n}.png ({os.path.getsize(os.path.join(ROOT,f'{n}.png'))//1024} KB)")
 print("Done!")
